import Provider from "@/SessionProvider";
import "./globals.css";
import NavBar from "@/components/NavBar";
import Footer from "@/components/Footer";

export const metadata = {
  title: "Discover Romania",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Provider>
        <body>
          <NavBar />
          {children}
          <Footer />
        </body>
      </Provider>
    </html>
  );
}
