// // import { SessionProvider } from "next-auth/react";


// import "./globals.css";
// import NavBar from "@/components/NavBar";
// import Footer from "@/components/Footer";

// export const metadata = {
//   title: "Discover Romania",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       {/* <SessionProvider session={session} refetchInterval={5 * 60}> */}
//         <body>
//           <NavBar />
//           {children}
//           <Footer />
//         </body>
//       {/* </SessionProvider> */}
//     </html>
//   );
// }
